### ISSUE TITLE
您好，我是使用这个脚本的时候出现了一个问题

### ISSUE THREAD

**Issue by baiyecha** [seanhuai/tumblr-source-list#3]
PS E:\code\git\tumblr-source-list> python .\app.py posturl https://wsyghf.tumblr.com/post/150478441406/
Traceback (most recent call last):
  File ".\app.py", line 5, in <module>
    from packages._funcs import *
  File "E:\code\git\tumblr-source-list\packages\_funcs.py", line 3, in <module>
    from packages._proxy import *
  File "E:\code\git\tumblr-source-list\packages\_proxy.py", line 3, in <module>
    from urllib import request
ImportError: cannot import name request

这是我的命令行信息，请问是什么问题导致的？这个脚本使用的python版本是多少呢~
谢谢~

**Comment by seanhuai** [comment]
应该是python的版本问题，这个脚本应该工作在python3
